// Starter narrative library. Seeded once on first run, then fully editable.
//
// Three habits baked into this set on purpose — maintain them in any new
// comment added here:
// 1. Every observational comment is phrased "appeared to be... at the time of
//    the inspection" — a visual inspection is a snapshot, not a warranty, and
//    that phrasing is what actually limits liability if a condition changes
//    or worsens after the fact.
// 2. Every comment that calls for a repair ends with the same recommendation
//    shape: "Evaluation by a licensed {tradesman} is recommended." (or
//    "Evaluation and {action} by a licensed {tradesman} is recommended."
//    when a specific action is also being called for) — never "Recommend
//    calling a...", "You should...", or any other phrasing. Consistent,
//    passive, non-alarmist wording is what keeps these defensible.
// 3. Variable facts (age, capacity) use a {Fill:label} placeholder instead of
//    a wall of near-duplicate comments — inserting one prompts for the value
//    once rather than needing "5 years", "8 years", "12 years" as separate
//    entries. See report/template.js item `tag`s for which of these overlap
//    with the 4-Point/Wind Mit forms, and item `group`s for which comment
//    `subgroup` a given checklist item lands on first in "From library".
//
// Organized by category (matches a checklist section title) then subgroup
// (matches a checklist item's `group`) — every section/subgroup pairing in
// report/template.js has at least a good/fair/deficient condition ladder
// here, plus the specific Florida-relevant defects worth a named entry.

// Bump whenever STARTER_COMMENTS changes in a way that should reach a device
// that already seeded its comment library — store.seedIfEmpty() upserts by
// (category + title) when this is newer than what's stored, so edits/adds
// here reach existing installs without wiping custom comments the inspector
// added themselves or their usage counts on existing ones.
export const COMMENTS_VERSION = 3;

export const STARTER_COMMENTS = [
  // ================================================================ SITE & GROUNDS
  { category: 'Site & Grounds', subgroup: 'Grading & Drainage', severity: 0, title: 'Grading — positive, away from structure',
    body: 'Site grading in the area observed appeared to fall away from the structure at the time of the inspection, directing surface water away from the foundation as intended.' },
  { category: 'Site & Grounds', subgroup: 'Grading & Drainage', severity: 1, title: 'Grading — negative, toward structure',
    body: 'Site grading in the area observed appeared to direct surface water toward the foundation rather than away from it, at the time of the inspection.',
    recommendation: 'Regrading to fall a minimum of 6 inches over the first 10 feet from the structure is recommended.' },
  { category: 'Site & Grounds', subgroup: 'Grading & Drainage', severity: 2, title: 'Standing water / ponding observed',
    body: 'Standing water or ponding was observed near the foundation at the time of the inspection, which may indicate inadequate grading or drainage.',
    recommendation: 'Evaluation by a qualified drainage or grading contractor is recommended.' },
  { category: 'Site & Grounds', subgroup: 'Driveway & Walkways', severity: 0, title: 'Driveway & walkways — good condition',
    body: 'The driveway and walkways appeared to be in good, serviceable condition at the time of the inspection.' },
  { category: 'Site & Grounds', subgroup: 'Driveway & Walkways', severity: 1, title: 'Driveway & walkways — cracking / settlement',
    body: 'Cracking and/or minor settlement was observed in the driveway and/or walkways at the time of the inspection, consistent with normal aging of concrete/asphalt paving. No trip hazard was noted.',
    recommendation: 'Routine sealing and monitoring is recommended.' },
  { category: 'Site & Grounds', subgroup: 'Driveway & Walkways', severity: 2, title: 'Driveway & walkways — trip hazard',
    body: 'A vertical displacement or gap sufficient to present a trip hazard was observed in the driveway and/or walkways at the time of the inspection.',
    recommendation: 'Correction by a qualified concrete/paving contractor is recommended.' },
  { category: 'Site & Grounds', subgroup: 'Vegetation & Fencing', severity: 0, title: 'Vegetation clearance — adequate',
    body: 'Vegetation appeared to be maintained with adequate clearance from the structure at the time of the inspection.' },
  { category: 'Site & Grounds', subgroup: 'Vegetation & Fencing', severity: 1, title: 'Vegetation contact with structure',
    body: 'Vegetation appeared to be in direct contact with the wall covering or roof at the time of the inspection, which can hold moisture against the structure and provide a pest access pathway.',
    recommendation: 'Trimming to maintain clearance from the structure is recommended.' },
  { category: 'Site & Grounds', subgroup: 'Vegetation & Fencing', severity: 1, title: 'Fencing / gate damaged',
    body: 'Fencing and/or a gate appeared to be damaged, leaning, or missing hardware at the time of the inspection.',
    recommendation: 'Repair by a qualified fencing contractor is recommended.' },

  // ================================================================ ROOF
  { category: 'Roof', subgroup: 'Roof Covering', severity: 0, title: 'Roof covering — new / recently installed',
    body: 'The roof covering appeared to be newly installed at the time of the inspection, with no visible signs of wear, damage, or deterioration.' },
  { category: 'Roof', subgroup: 'Roof Covering', severity: 0, title: 'Roof covering — good condition',
    body: 'The roof covering appeared to be in good condition at the time of the inspection, with wear consistent with normal use and age. No repair appeared necessary at this time.' },
  { category: 'Roof', subgroup: 'Roof Covering', severity: 1, title: 'Roof covering — fair condition, aging',
    body: 'The roof covering appeared to be in fair condition at the time of the inspection, showing signs of aging consistent with its age, including some granule loss and minor wear. No active leakage was observed. Continued monitoring and routine maintenance is recommended.' },
  { category: 'Roof', subgroup: 'Roof Covering', severity: 2, title: 'Roof covering — nearing end of service life',
    body: 'The roof covering appeared to be nearing the end of its serviceable life at the time of the inspection, with wear consistent with age including granule loss, curling, or cracking in isolated areas. No active leakage was observed at the time of the inspection. Budgeting for replacement in the near term, and monitoring for developing issues, is recommended.' },
  { category: 'Roof', subgroup: 'Roof Covering', severity: 3, title: 'Roof covering — end of service life / replacement recommended',
    body: 'The roof covering appeared to be at or beyond the end of its serviceable life at the time of the inspection, exhibiting significant wear including granule loss, curling, cracking, and/or missing material.',
    recommendation: 'Evaluation and replacement by a licensed roofing contractor is recommended.' },
  { category: 'Roof', subgroup: 'Roof Covering', severity: 1, title: 'Roof age (fill-in)',
    body: 'The roof covering was estimated to be approximately {Fill:years} years old at the time of the inspection, based on its visible condition and permit records where available.' },
  { category: 'Roof', subgroup: 'Flashing & Drainage', severity: 0, title: 'Flashing & penetrations — properly sealed',
    body: 'Roof flashing and penetrations appeared to be properly installed and sealed at the time of the inspection.' },
  { category: 'Roof', subgroup: 'Flashing & Drainage', severity: 2, title: 'Flashing deteriorated / improperly sealed',
    body: 'Roof flashing at a penetration, wall intersection, or valley appeared to be deteriorated, rusted, or improperly sealed at the time of the inspection, which can allow water intrusion.',
    recommendation: 'Evaluation and correction by a licensed roofing contractor is recommended.' },
  { category: 'Roof', subgroup: 'Flashing & Drainage', severity: 0, title: 'Gutters & downspouts — functional',
    body: 'Gutters and downspouts appeared to be properly secured and directing water away from the structure at the time of the inspection.' },
  { category: 'Roof', subgroup: 'Flashing & Drainage', severity: 1, title: 'Gutters damaged, clogged, or discharging at foundation',
    body: 'Gutters and/or downspouts appeared to be damaged, disconnected, clogged with debris, or discharging directly at the foundation rather than away from it, at the time of the inspection.',
    recommendation: 'Cleaning, repair, and extension of downspout discharge away from the foundation is recommended.' },
  { category: 'Roof', subgroup: 'Flashing & Drainage', severity: 0, title: 'No gutters observed',
    body: 'No gutters were observed on the structure at the time of the inspection. Gutters were not present at the time of the inspection and their absence is noted for information only; roof drainage relies on grading at the drip line.' },
  { category: 'Roof', subgroup: 'Flashing & Drainage', severity: 1, title: 'Fascia / soffit deterioration at roofline',
    body: 'Fascia and/or soffit at the roofline appeared to show deterioration, staining, or gaps at the time of the inspection.',
    recommendation: 'Evaluation and repair by a qualified contractor is recommended.' },
  { category: 'Roof', subgroup: 'Roof Covering', severity: 3, title: 'Active roof leak observed',
    body: 'Evidence of active or recent roof leakage was observed at the time of the inspection, including staining, moisture, or active intrusion at the underside of the roof deck and/or ceiling below.',
    recommendation: 'Evaluation and repair by a licensed roofing contractor is recommended.' },

  // ================================================================ EXTERIOR
  { category: 'Exterior', subgroup: 'Wall Covering', severity: 0, title: 'Wall covering — good condition',
    body: 'The exterior wall covering appeared to be in good condition at the time of the inspection, with no significant cracking, damage, or deterioration observed.' },
  { category: 'Exterior', subgroup: 'Wall Covering', severity: 1, title: 'Wall covering — fair condition, minor wear',
    body: 'The exterior wall covering appeared to be in fair condition at the time of the inspection, with minor wear, hairline cracking, or areas of peeling/fading paint consistent with age. Routine maintenance is recommended.' },
  { category: 'Exterior', subgroup: 'Wall Covering', severity: 1, title: 'Stucco cracking',
    body: 'Cracking was observed in the stucco wall covering at the time of the inspection. Unsealed cracks can admit moisture into the wall assembly over time.',
    recommendation: 'Sealing, monitoring, and further evaluation if cracking widens is recommended.' },
  { category: 'Exterior', subgroup: 'Wall Covering', severity: 2, title: 'Wall covering — significant damage / moisture path',
    body: 'The exterior wall covering appeared to have significant cracking, separation, or damage at the time of the inspection, creating a potential path for moisture intrusion.',
    recommendation: 'Evaluation and repair by a qualified contractor is recommended.' },
  { category: 'Exterior', subgroup: 'Windows, Doors & Trim', severity: 0, title: 'Windows & doors — functional',
    body: 'Exterior windows and doors operated as intended and appeared to be properly sealed at the time of the inspection.' },
  { category: 'Exterior', subgroup: 'Windows, Doors & Trim', severity: 1, title: 'Caulk / sealant deteriorated at openings',
    body: 'Caulk and/or sealant at window and door openings appeared to be cracked, missing, or deteriorated at the time of the inspection, which can allow water intrusion at the opening.',
    recommendation: 'Re-caulking by a qualified contractor is recommended.' },
  { category: 'Exterior', subgroup: 'Windows, Doors & Trim', severity: 2, title: 'Window or door inoperable / damaged',
    body: 'A window or exterior door did not operate as intended, or showed damaged glazing or hardware, at the time of the inspection.',
    recommendation: 'Evaluation and repair by a qualified contractor is recommended.' },
  { category: 'Exterior', subgroup: 'Windows, Doors & Trim', severity: 2, title: 'Wood rot at trim / fascia',
    body: 'Deteriorated and rotted wood appeared to be present at exterior trim or fascia components at the time of the inspection.',
    recommendation: 'Repair or replacement of affected components, and correction of the moisture source, by a qualified contractor is recommended.' },
  { category: 'Exterior', subgroup: 'Porches & Attachments', severity: 0, title: 'Porches / decks — good condition',
    body: 'Porches, decks, and/or balconies appeared to be structurally sound and in good condition at the time of the inspection.' },
  { category: 'Exterior', subgroup: 'Porches & Attachments', severity: 2, title: 'Deteriorated / soft decking observed',
    body: 'Soft spots, deterioration, or damaged fasteners were observed at a porch, deck, or balcony at the time of the inspection.',
    recommendation: 'Evaluation and repair by a qualified contractor is recommended.' },

  // ================================================================ STRUCTURE & FOUNDATION
  { category: 'Structure & Foundation', subgroup: 'Foundation', severity: 0, title: 'Foundation — good condition',
    body: 'The foundation appeared to be in good condition at the time of the inspection, with no significant cracking, settlement, or deficiencies observed within the visible and accessible areas.' },
  { category: 'Structure & Foundation', subgroup: 'Foundation', severity: 1, title: 'Foundation — minor cosmetic cracking',
    body: 'Hairline or cosmetic cracking was observed at the foundation at the time of the inspection, typical of normal curing and settlement and not considered structurally significant. Monitoring is recommended.' },
  { category: 'Structure & Foundation', subgroup: 'Foundation', severity: 2, title: 'Foundation — moderate cracking, monitor',
    body: 'Moderate cracking was observed at the foundation at the time of the inspection. This did not appear to be actively progressing at the time of the inspection, but should be monitored.',
    recommendation: 'Monitoring, with evaluation by a qualified structural contractor if cracking widens or progresses, is recommended.' },
  { category: 'Structure & Foundation', subgroup: 'Foundation', severity: 3, title: 'Foundation — significant cracking, evaluation recommended',
    body: 'Significant cracking, displacement, or other signs of possible structural movement were observed at the foundation at the time of the inspection.',
    recommendation: 'Evaluation by a licensed structural engineer is recommended.' },
  { category: 'Structure & Foundation', subgroup: 'Framing', severity: 0, title: 'Framing — good condition',
    body: 'Visible framing components appeared to be in good condition at the time of the inspection, with no evidence of moisture damage, deterioration, or unusual deflection.' },
  { category: 'Structure & Foundation', subgroup: 'Framing', severity: 2, title: 'Framing — moisture damage / deterioration observed',
    body: 'Visible framing components showed evidence of moisture damage or deterioration at the time of the inspection.',
    recommendation: 'Evaluation by a qualified structural contractor, along with correction of the moisture source, is recommended.' },
  { category: 'Structure & Foundation', subgroup: 'Framing', severity: 3, title: 'Evidence of settlement or structural movement',
    body: 'Signs consistent with settlement or structural movement — such as out-of-level floors, racked door/window openings, or displaced framing — were observed at the time of the inspection.',
    recommendation: 'Evaluation by a licensed structural engineer is recommended.' },
  { category: 'Structure & Foundation', subgroup: 'Framing', severity: 3, title: 'Evidence of wood-destroying organism activity',
    body: 'Evidence consistent with wood-destroying organism activity (e.g. mud tubes, frass, or damaged wood) was observed at the time of the inspection. This observation is reported only; a WDO inspection is a separate licensed service and this report does not constitute one.',
    recommendation: 'Evaluation by a licensed WDO/pest control inspector is recommended.' },

  // ================================================================ ATTIC, INSULATION & VENTILATION
  { category: 'Attic, Insulation & Ventilation', subgroup: 'Attic Structure', severity: 0, title: 'Attic structure — good condition',
    body: 'The roof sheathing/decking and truss/rafter framing visible in the attic appeared to be in good condition at the time of the inspection, with no evidence of moisture intrusion or damage.' },
  { category: 'Attic, Insulation & Ventilation', subgroup: 'Attic Structure', severity: 2, title: 'Moisture staining on sheathing / framing',
    body: 'Moisture staining was observed on the roof sheathing and/or framing in the attic at the time of the inspection. The source could not be confirmed as active at the time of the inspection.',
    recommendation: 'Evaluation by a licensed roofing contractor to confirm and correct the source is recommended.' },
  { category: 'Attic, Insulation & Ventilation', subgroup: 'Attic Structure', severity: 3, title: 'Damaged truss / rafter framing',
    body: 'Visible damage — cutting, splitting, or sagging — was observed in the truss or rafter framing at the time of the inspection.',
    recommendation: 'Evaluation by a licensed structural engineer is recommended.' },
  { category: 'Attic, Insulation & Ventilation', subgroup: 'Insulation', severity: 0, title: 'Insulation — adequate depth and coverage',
    body: 'Attic insulation appeared to be present at an adequate depth with generally even coverage at the time of the inspection.' },
  { category: 'Attic, Insulation & Ventilation', subgroup: 'Insulation', severity: 1, title: 'Insulation — uneven / thin coverage',
    body: 'Attic insulation appeared to be thin or unevenly distributed in one or more areas at the time of the inspection, below current recommended levels for the region.',
    recommendation: 'Supplementing insulation to current recommended levels is recommended.' },
  { category: 'Attic, Insulation & Ventilation', subgroup: 'Insulation', severity: 2, title: 'Insulation — missing in areas',
    body: 'Attic insulation appeared to be missing entirely in one or more accessible areas at the time of the inspection.',
    recommendation: 'Installation of insulation to current recommended levels is recommended.' },
  { category: 'Attic, Insulation & Ventilation', subgroup: 'Ventilation', severity: 0, title: 'Attic ventilation — adequate',
    body: 'Attic ventilation appeared to be adequate at the time of the inspection, with intake and exhaust venting present and unobstructed.' },
  { category: 'Attic, Insulation & Ventilation', subgroup: 'Ventilation', severity: 2, title: 'Attic ventilation — inadequate',
    body: 'The attic ventilation appeared to be inadequate at the time of the inspection. Modern construction requires vent openings along the ridge or on the slopes; without them, humid air has nowhere to go and will sit in the attic, increasing the risk of microbial growth. Some growth was already observed at the time of the inspection.',
    recommendation: 'Installation of additional ventilation, to protect interior comfort, prolong the life of the roofing materials, and prevent continued microbial growth, is recommended.' },
  { category: 'Attic, Insulation & Ventilation', subgroup: 'Ventilation', severity: 1, title: 'Exhaust fans not terminated to exterior',
    body: 'One or more bathroom or other exhaust fans appeared to terminate into the attic space rather than to the exterior, at the time of the inspection. This can introduce moisture into the attic.',
    recommendation: 'Correction to terminate all exhaust fans to the exterior is recommended.' },

  // ================================================================ ELECTRICAL
  { category: 'Electrical', subgroup: 'Electrical Panel', severity: 0, title: 'Electrical panel — good condition',
    body: 'The electrical panel appeared to be properly installed and in good condition at the time of the inspection, with circuits identified and no obvious deficiencies observed.' },
  { category: 'Electrical', subgroup: 'Electrical Panel', severity: 1, title: 'Electrical panel — minor deferred maintenance',
    body: 'The electrical panel appeared to be functional at the time of the inspection but showed minor deferred maintenance, such as an incomplete circuit directory or missing knockout covers. Correction as routine maintenance is recommended.' },
  { category: 'Electrical', subgroup: 'Electrical Panel', severity: 2, title: 'Electrical panel — deficiencies observed',
    body: 'The electrical panel appeared to have deficiencies at the time of the inspection that warrant further evaluation.',
    recommendation: 'Evaluation and correction by a licensed electrician is recommended.' },
  { category: 'Electrical', subgroup: 'Electrical Panel', severity: 1, title: 'Electrical panel age (fill-in)',
    body: 'The electrical panel was estimated to be approximately {Fill:years} years old at the time of the inspection, based on its visible condition and labeling.' },
  { category: 'Electrical', subgroup: 'Electrical Panel', severity: 3, title: 'Federal Pacific Stab-Lok panel',
    body: 'The electrical distribution panel appeared to be a Federal Pacific Electric Stab-Lok panel at the time of the inspection. These panels have a documented history of breakers failing to trip under overload conditions, presenting a potential fire hazard, and are frequently declined or flagged by insurers.',
    recommendation: 'Evaluation and replacement by a licensed electrician is recommended.' },
  { category: 'Electrical', subgroup: 'Electrical Panel', severity: 3, title: 'Zinsco / Sylvania panel',
    body: 'The electrical panel appeared to be a Zinsco or Sylvania-Zinsco type panel at the time of the inspection. These panels are known for bus bar damage and breakers that may fail to trip, and are commonly declined by insurers.',
    recommendation: 'Evaluation and replacement by a licensed electrician is recommended.' },
  { category: 'Electrical', subgroup: 'Electrical Panel', severity: 3, title: 'Double-tapped breaker',
    body: 'Two or more conductors appeared to be terminated under a single breaker lug not listed for multiple conductors at the time of the inspection. This condition can result in loose connections and overheating.',
    recommendation: 'Correction by a licensed electrician is recommended.' },
  { category: 'Electrical', subgroup: 'Electrical Panel', severity: 0, title: 'Electric meter location (fill-in)',
    body: 'The electric meter is located at: {Fill:location}.' },
  { category: 'Electrical', subgroup: 'Electrical Panel', severity: 0, title: 'Main panel location (fill-in)',
    body: 'The main electrical service panel is located at: {Fill:location}.' },
  { category: 'Electrical', subgroup: 'Wiring & Safety', severity: 0, title: 'Wiring & devices — good condition',
    body: 'Representative wiring, receptacles, switches, and light fixtures appeared to be in good, functional condition at the time of the inspection.' },
  { category: 'Electrical', subgroup: 'Wiring & Safety', severity: 3, title: 'Missing GFCI protection',
    body: 'Receptacles in wet or damp locations appeared to lack ground-fault circuit interrupter protection as required for the location, at the time of the inspection.',
    recommendation: 'Installation of GFCI protection by a licensed electrician is recommended.' },
  { category: 'Electrical', subgroup: 'Wiring & Safety', severity: 2, title: 'Missing AFCI protection',
    body: 'One or more circuits appeared to lack arc-fault circuit interrupter protection as required for the circuit type, at the time of the inspection.',
    recommendation: 'Evaluation and correction by a licensed electrician is recommended.' },
  { category: 'Electrical', subgroup: 'Wiring & Safety', severity: 4, title: 'Open splices / missing box covers',
    body: 'Exposed wiring splices outside of an approved enclosure, and/or junction boxes missing covers, were observed at the time of the inspection. This condition presents a potential shock and fire hazard.',
    recommendation: 'Correction by a licensed electrician is recommended.' },
  { category: 'Electrical', subgroup: 'Wiring & Safety', severity: 3, title: 'Aluminum branch circuit wiring',
    body: 'Single-strand aluminum branch circuit wiring appeared to be present at the time of the inspection. Aluminum conductors of this type are prone to oxidation and loose connections at terminations over time, and insurers frequently require remediation.',
    recommendation: 'Evaluation by a licensed electrician, with remediation using an approved method (e.g. COPALUM or AlumiConn connectors), is recommended.' },
  { category: 'Electrical', subgroup: 'Wiring & Safety', severity: 2, title: 'Smoke alarms past service life',
    body: 'Smoke alarms present appeared to exceed the manufacturer’s recommended 10-year service life, or were missing from one or more required locations, at the time of the inspection.',
    recommendation: 'Replacement and installation in all required locations is recommended.' },
  { category: 'Electrical', subgroup: 'Wiring & Safety', severity: 2, title: 'Knob-and-tube wiring active',
    body: 'Active knob-and-tube wiring appeared to be present at the time of the inspection. This legacy wiring method lacks a ground conductor and is commonly a concern for insurers.',
    recommendation: 'Evaluation by a licensed electrician is recommended.' },

  // ================================================================ PLUMBING
  { category: 'Plumbing', subgroup: 'Water Heater', severity: 0, title: 'Water heater — good condition',
    body: 'The water heater appeared to be properly installed and functioning at the time of the inspection, with no signs of leakage or corrosion observed.' },
  { category: 'Plumbing', subgroup: 'Water Heater', severity: 1, title: 'Water heater — approaching service life expectations',
    body: 'The water heater appeared to be functioning at the time of the inspection but is approaching the upper end of its typical 10–12 year service life. No active leakage was observed. Monitoring and budgeting for eventual replacement is recommended.' },
  { category: 'Plumbing', subgroup: 'Water Heater', severity: 2, title: 'Water heater — beyond typical service life',
    body: 'The water heater appeared to be at or beyond its typical 10–12 year service life at the time of the inspection. Tank failure at end of life can result in uncontrolled water discharge.',
    recommendation: 'Budgeting for replacement by a licensed plumber is recommended.' },
  { category: 'Plumbing', subgroup: 'Water Heater', severity: 1, title: 'Water heater age (fill-in)',
    body: 'The water heater was estimated to be approximately {Fill:years} years old at the time of the inspection, based on the manufacture date on its data plate.' },
  { category: 'Plumbing', subgroup: 'Water Heater', severity: 0, title: 'Water heater capacity (fill-in)',
    body: 'The water heater has an approximate capacity of {Fill:gallons} gallons, per its data plate.' },
  { category: 'Plumbing', subgroup: 'Water Heater', severity: 2, title: 'Missing water heater drain pan',
    body: 'The water heater appeared to be installed without a drain pan and drain line at the time of the inspection, in a location where a leak would damage the finished interior.',
    recommendation: 'Installation of a drain pan piped to an approved discharge point, by a licensed plumber, is recommended.' },
  { category: 'Plumbing', subgroup: 'Water Heater', severity: 3, title: 'TPR discharge piping improper',
    body: 'The temperature and pressure relief discharge line appeared to terminate improperly, was reduced in size, or was missing, at the time of the inspection. This is a scald and pressure-vessel safety concern.',
    recommendation: 'Correction by a licensed plumber, terminating full-size within 6 inches of the floor or to the exterior, is recommended.' },
  { category: 'Plumbing', subgroup: 'Supply & Fixtures', severity: 0, title: 'Fixtures — good condition',
    body: 'Plumbing fixtures observed (sinks, tubs, showers, toilets) appeared to be functional with adequate water flow and drainage, and no active leaks, at the time of the inspection.' },
  { category: 'Plumbing', subgroup: 'Supply & Fixtures', severity: 3, title: 'Polybutylene supply piping',
    body: 'Polybutylene water supply piping appeared to be present at the time of the inspection. This material is subject to premature failure and is a common cause of insurance decline or non-renewal in Florida.',
    recommendation: 'Evaluation and repiping by a licensed plumber is recommended.' },
  { category: 'Plumbing', subgroup: 'Supply & Fixtures', severity: 2, title: 'Active leak at fixture',
    body: 'An active leak appeared to be present at the fixture supply or drain connection at the time of the inspection.',
    recommendation: 'Repair by a licensed plumber is recommended.' },
  { category: 'Plumbing', subgroup: 'Supply & Fixtures', severity: 1, title: 'Low water flow / pressure',
    body: 'Water flow at one or more fixtures appeared to be lower than expected at the time of the inspection, which may indicate a restriction, aerator buildup, or supply piping condition.',
    recommendation: 'Evaluation by a licensed plumber is recommended.' },
  { category: 'Plumbing', subgroup: 'Water Heater', severity: 0, title: 'Water shutoff location (fill-in)',
    body: 'The domestic water supply main shut-off is located at: {Fill:location}.' },
  { category: 'Plumbing', subgroup: 'Drain, Waste & Sewage', severity: 0, title: 'Drain, waste & vent — functional',
    body: 'The drain, waste, and vent system appeared to be functioning as intended at the time of the inspection, with adequate drainage and no evidence of leaks at accessible connections.' },
  { category: 'Plumbing', subgroup: 'Drain, Waste & Sewage', severity: 2, title: 'Slow or inadequate drainage',
    body: 'Slow or inadequate drainage was observed at one or more fixtures at the time of the inspection, which may indicate a partial obstruction in the drain, waste, or vent system.',
    recommendation: 'Evaluation by a licensed plumber is recommended.' },
  { category: 'Plumbing', subgroup: 'Drain, Waste & Sewage', severity: 0, title: 'Septic system present — not evaluated',
    body: 'The property is served by a septic system. Septic tanks, drain fields, and their components are underground and not visible for inspection; this inspection does not include evaluation of the septic system. A separate septic evaluation by a licensed septic contractor is recommended, particularly for older or unknown-age systems.' },
  { category: 'Plumbing', subgroup: 'Drain, Waste & Sewage', severity: 0, title: 'Public sewer connection',
    body: 'The property appeared to be connected to the public sewer system at the time of the inspection. The sewer lateral itself is underground and outside the scope of a visual inspection.' },

  // ================================================================ HVAC
  { category: 'HVAC', subgroup: 'HVAC System', severity: 0, title: 'HVAC system — good condition',
    body: 'The HVAC system appeared to be functioning normally at the time of the inspection, responding to thermostat controls with a temperature differential within the normal range.' },
  { category: 'HVAC', subgroup: 'HVAC System', severity: 1, title: 'HVAC system — approaching service life expectations',
    body: 'The HVAC system appeared to be functioning at the time of the inspection but is approaching the upper end of its typical 12–15 year service life. Continued routine servicing and budgeting for eventual replacement is recommended.' },
  { category: 'HVAC', subgroup: 'HVAC System', severity: 2, title: 'HVAC system — beyond typical service life',
    body: 'The HVAC system appeared to be at or beyond its typical 12–15 year service life at the time of the inspection. Remaining service life cannot be predicted from a visual inspection.',
    recommendation: 'Evaluation by a licensed HVAC contractor, with budgeting for eventual replacement, is recommended.' },
  { category: 'HVAC', subgroup: 'HVAC System', severity: 1, title: 'HVAC system age (fill-in)',
    body: 'The HVAC system was estimated to be approximately {Fill:years} years old at the time of the inspection, based on the manufacture date on its data plate.' },
  { category: 'HVAC', subgroup: 'Airflow & Ductwork', severity: 2, title: 'Inadequate temperature differential',
    body: 'The measured temperature differential across the evaporator fell outside the normal 14–22°F range at the time of the inspection, which may indicate a refrigerant charge, airflow, or capacity concern.',
    recommendation: 'Evaluation and service by a licensed HVAC contractor is recommended.' },
  { category: 'HVAC', subgroup: 'Airflow & Ductwork', severity: 1, title: 'Condensate drain concerns',
    body: 'The condensate drain appeared to show evidence of prior overflow, and/or did not appear to be properly trapped or equipped with a functional safety float switch, at the time of the inspection.',
    recommendation: 'Service by a licensed HVAC contractor is recommended.' },
  { category: 'HVAC', subgroup: 'Airflow & Ductwork', severity: 0, title: 'Filter dirty',
    body: 'The air filter appeared to be heavily loaded at the time of the inspection, restricting airflow and reducing system efficiency.',
    recommendation: 'Replacement and a regular filter change schedule is recommended.' },
  { category: 'HVAC', subgroup: 'Airflow & Ductwork', severity: 2, title: 'Damaged / disconnected duct',
    body: 'Ductwork appeared to be damaged, disconnected, or had deteriorated insulation at the time of the inspection, resulting in conditioned air loss.',
    recommendation: 'Repair by a licensed HVAC contractor is recommended.' },
  { category: 'HVAC', subgroup: 'Airflow & Ductwork', severity: 0, title: 'Thermostat & controls — functional',
    body: 'The thermostat and system controls responded normally when tested at the time of the inspection.' },

  // ================================================================ INTERIOR
  { category: 'Interior', subgroup: 'Surfaces', severity: 0, title: 'Interior surfaces — good condition',
    body: 'Ceilings, walls, and floors observed appeared to be in good condition at the time of the inspection, with wear consistent with normal use.' },
  { category: 'Interior', subgroup: 'Surfaces', severity: 1, title: 'Moisture staining observed',
    body: 'Moisture staining was observed on the ceiling or wall finish at the time of the inspection. The stain did not read elevated on a moisture meter at the time of the inspection, but the source should be confirmed.',
    recommendation: 'Confirming the source has been repaired, and continued monitoring, is recommended.' },
  { category: 'Interior', subgroup: 'Surfaces', severity: 2, title: 'Evidence of mold-like growth',
    body: 'Growth consistent with mold or other microbial growth was observed at the time of the inspection. This is reported as a visual observation only; laboratory testing and remediation are separate services outside the scope of this inspection.',
    recommendation: 'Evaluation by a qualified mold/indoor air quality professional is recommended.' },
  { category: 'Interior', subgroup: 'Openings & Safety', severity: 0, title: 'Doors, windows & stairs — functional',
    body: 'Interior doors, windows, and stairs/railings operated and appeared to be in good condition at the time of the inspection.' },
  { category: 'Interior', subgroup: 'Openings & Safety', severity: 4, title: 'Missing / improper guard or handrail',
    body: 'A required guard or handrail appeared to be missing, loose, or had openings permitting passage of a 4-inch sphere, at the time of the inspection. This is a fall hazard.',
    recommendation: 'Correction to current safety standards is recommended.' },
  { category: 'Interior', subgroup: 'Openings & Safety', severity: 1, title: 'Fireplace / chimney — not evaluated for use',
    body: 'A fireplace and/or chimney is present. This inspection is limited to a visual review of readily accessible components; the flue and firebox are not internally inspected as part of a general home inspection.',
    recommendation: 'Evaluation and cleaning by a certified chimney sweep prior to use is recommended.' },

  // ================================================================ KITCHEN & APPLIANCES
  { category: 'Kitchen & Appliances', subgroup: 'Cabinets & Counters', severity: 0, title: 'Cabinets & counters — good condition',
    body: 'Kitchen cabinets, countertops, and the sink/faucet appeared to be in good, functional condition at the time of the inspection.' },
  { category: 'Kitchen & Appliances', subgroup: 'Cabinets & Counters', severity: 2, title: 'Water damage under sink',
    body: 'Water staining or damage was observed at the cabinet floor beneath the kitchen sink at the time of the inspection, consistent with a past or present leak.',
    recommendation: 'Evaluation by a licensed plumber to confirm the source is recommended.' },
  { category: 'Kitchen & Appliances', subgroup: 'Appliances', severity: 0, title: 'Appliances — tested, functional',
    body: 'Built-in appliances were operated using normal controls and appeared to function as intended at the time of the inspection.' },
  { category: 'Kitchen & Appliances', subgroup: 'Appliances', severity: 0, title: 'Appliance not tested',
    body: 'This appliance was not operated as part of the inspection (not connected, no supply, or outside the scope of a general home inspection) and no representation is made as to its condition or function.' },
  { category: 'Kitchen & Appliances', subgroup: 'Appliances', severity: 2, title: 'Appliance found inoperative',
    body: 'This appliance did not respond to normal operating controls at the time of the inspection.',
    recommendation: 'Evaluation by a qualified appliance technician is recommended.' },

  // ================================================================ BATHROOMS
  { category: 'Bathrooms', subgroup: 'Fixtures', severity: 0, title: 'Bathroom fixtures — good condition',
    body: 'Toilets, sinks, and the shower/tub appeared to be properly installed and functioning at the time of the inspection.' },
  { category: 'Bathrooms', subgroup: 'Fixtures', severity: 1, title: 'Caulk / grout deteriorated at tub or shower',
    body: 'Caulk and/or grout at the tub or shower surround appeared to be cracked, missing, or deteriorated at the time of the inspection, which can allow water intrusion behind the finished surface.',
    recommendation: 'Re-caulking/re-grouting as routine maintenance is recommended.' },
  { category: 'Bathrooms', subgroup: 'Ventilation & Moisture', severity: 0, title: 'Ventilation — adequate',
    body: 'The bathroom appeared to have adequate ventilation, via an exhaust fan and/or operable window, at the time of the inspection.' },
  { category: 'Bathrooms', subgroup: 'Ventilation & Moisture', severity: 1, title: 'No exhaust fan or window',
    body: 'This bathroom did not appear to have an exhaust fan or operable window for ventilation at the time of the inspection, which can contribute to elevated humidity and microbial growth.',
    recommendation: 'Installation of an exhaust fan vented to the exterior is recommended.' },
  { category: 'Bathrooms', subgroup: 'Ventilation & Moisture', severity: 2, title: 'Evidence of moisture damage',
    body: 'Evidence of moisture damage — staining, softness, or deterioration of finished surfaces — was observed in this bathroom at the time of the inspection.',
    recommendation: 'Evaluation and repair by a qualified contractor, along with correction of the moisture source, is recommended.' },

  // ================================================================ LAUNDRY
  { category: 'Laundry', subgroup: 'Laundry', severity: 0, title: 'Laundry hookups — good condition',
    body: 'Washer supply valves, drain, and dryer power supply appeared to be properly installed and in good condition at the time of the inspection.' },
  { category: 'Laundry', subgroup: 'Laundry', severity: 2, title: 'Supply valve leak observed',
    body: 'A leak was observed at a washer supply valve or connection at the time of the inspection.',
    recommendation: 'Repair by a licensed plumber is recommended.' },
  { category: 'Laundry', subgroup: 'Laundry', severity: 2, title: 'Dryer exhaust — damaged or non-rigid duct',
    body: 'The dryer exhaust duct appeared to be damaged, excessively long, or of a non-rigid (flexible vinyl/foil) type at the time of the inspection. Improper dryer venting is a recognized fire hazard due to lint accumulation.',
    recommendation: 'Correction with rigid metal ducting and proper exterior termination, by a qualified contractor, is recommended.' },

  // ================================================================ GARAGE & CARPORT
  { category: 'Garage & Carport', subgroup: 'Doors & Openers', severity: 0, title: 'Garage door & opener — functional',
    body: 'The vehicle door and automatic opener operated normally, with the safety reverse and photo-eye sensors functioning as intended, at the time of the inspection.' },
  { category: 'Garage & Carport', subgroup: 'Doors & Openers', severity: 4, title: 'Garage door safety reverse failed',
    body: 'The automatic vehicle door did not reverse on contact, or on obstruction of the photo-eye sensors, at the time of the inspection. This is an entrapment hazard.',
    recommendation: 'Adjustment or repair by a qualified garage door technician is recommended.' },
  { category: 'Garage & Carport', subgroup: 'Structure & Electrical', severity: 0, title: 'Garage structure & electrical — good condition',
    body: 'The garage floor/slab, electrical devices, and GFCI protection appeared to be in good, functional condition at the time of the inspection.' },
  { category: 'Garage & Carport', subgroup: 'Structure & Electrical', severity: 3, title: 'Fire separation compromised',
    body: 'The fire separation between the garage and living space appeared to be penetrated or damaged, and/or the door did not appear to be self-closing and fire-rated, at the time of the inspection.',
    recommendation: 'Restoration of the required fire separation is recommended.' },
  { category: 'Garage & Carport', subgroup: 'Structure & Electrical', severity: 1, title: 'Garage floor/slab cracking',
    body: 'Cracking was observed in the garage floor/slab at the time of the inspection, typical of normal curing and settlement and not considered structurally significant at the time of the inspection.' },

  // ================================================================ POOL & SPA
  { category: 'Pool & Spa', subgroup: 'Pool Equipment', severity: 0, title: 'Pool equipment — functional',
    body: 'The pool shell, deck, pump, filter, and associated equipment appeared to be in good, functional condition at the time of the inspection.' },
  { category: 'Pool & Spa', subgroup: 'Pool Equipment', severity: 2, title: 'Pump / filter / plumbing deficiency',
    body: 'A deficiency was observed at the pool pump, filter, or associated plumbing at the time of the inspection, such as a leak, unusual noise, or reduced flow.',
    recommendation: 'Evaluation by a licensed pool contractor is recommended.' },
  { category: 'Pool & Spa', subgroup: 'Pool Equipment', severity: 3, title: 'Missing electrical bonding / GFCI at pool equipment',
    body: 'Pool equipment did not appear to have the required equipotential bonding and/or GFCI protection at the time of the inspection. This is a shock hazard.',
    recommendation: 'Evaluation and correction by a licensed electrician is recommended.' },
  { category: 'Pool & Spa', subgroup: 'Safety Barrier', severity: 0, title: 'Safety barrier — compliant, in place',
    body: 'A safety barrier (enclosure, fencing, and/or self-closing/self-latching gate) appeared to be in place around the pool at the time of the inspection.' },
  { category: 'Pool & Spa', subgroup: 'Safety Barrier', severity: 4, title: 'Missing / non-compliant safety barrier',
    body: 'The pool did not appear to have a compliant safety barrier — enclosure, fencing, or a self-closing/self-latching gate — at the time of the inspection. This is a drowning hazard, particularly for young children, and is commonly required by Florida law and by insurers.',
    recommendation: 'Installation of a compliant safety barrier is recommended.' },

  // ================================================================ GENERAL (fallback, any section)
  { category: 'General', severity: 0, title: 'Serviceable at time of inspection',
    body: 'This component appeared to be functioning as intended at the time of the inspection. No deficiencies were observed within the scope of a visual inspection.' },
  { category: 'General', severity: 0, title: 'Not inspected — inaccessible',
    body: 'This component could not be inspected because it was not accessible at the time of the inspection. No representation is made as to its condition.',
    recommendation: 'Further inspection once access is provided is recommended.' },
  { category: 'General', severity: 1, title: 'Deferred maintenance',
    body: 'The component appeared to show deferred maintenance typical for its age, at the time of the inspection. Attention now will extend its service life.',
    recommendation: 'Routine maintenance and monitoring is recommended.' },
  { category: 'General', severity: 0, title: 'Not present',
    body: 'This component was not present at the property at the time of the inspection.' },
];
